server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats
    username: root
    password: root

  config:
    activate:
      on-profile: ci,test
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:stats-db
      username: test
      password: test