server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-invalid: true
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats-db
    username: asd
    password: asd

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stats-db
    username: test
    password: test