DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
    app       VARCHAR(254)                                         NOT NULL,
    uri       TEXT                                                 NOT NULL,
    ip        VARCHAR(254)                                         NOT NULL,
    timestamp TIMESTAMP                                            NOT NULL
)