spring:

  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm-db
    username: test
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
