DROP TABLE IF EXISTS users, categories, locations, events CASCADE;



CREATE TABLE IF NOT EXISTS categories (
    id   SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT UQ_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id    SERIAL PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT UQ_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat REAL,
    lon REAL
);
CREATE TABLE IF NOT EXISTS event (
    id                  SERIAL PRIMARY KEY,
    ANNOTATION          VARCHAR(2000),
    category_id         BIGINT,
    confirm_requests    BIGINT,
    created_on          TIMESTAMP,
    description         VARCHAR(7000),
    event_date          TIMESTAMP,
    initiator_id        BIGINT,
    location_id         BIGINT,
    paid                BOOLEAN,
    participant_limit   INT,
    published_on        TIMESTAMP,
    request_moderation  BOOLEAN,
    state               VARCHAR(50),
    title               VARCHAR(125),
    views               BIGINT,
    CONSTRAINT FK_category_id FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT FK_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT FK_location_id FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id                  SERIAL PRIMARY KEY,
    title               VARCHAR(50),
    pinned              BOOLEAN
);